/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdRouteImport } from './routes/user.$id'
import { Route as ReviewIdRouteImport } from './routes/review.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as BrowseCategoryRouteImport } from './routes/browse.$category'
import { Route as AuthenticatedSubmitListingRouteImport } from './routes/_authenticated/submit-listing'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMySavedRouteImport } from './routes/_authenticated/my-saved'
import { Route as AuthenticatedMyListingsRouteImport } from './routes/_authenticated/my-listings'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedCompleteDealerProfileRouteImport } from './routes/_authenticated/complete-dealer-profile'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/account-settings'
import { Route as AuthenticatedEditListingIdRouteImport } from './routes/_authenticated/edit-listing.$id'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminListingsRouteImport } from './routes/_authenticated/admin/listings'
import { Route as AuthenticatedAdminDealersRouteImport } from './routes/_authenticated/admin/dealers'
import { Route as AuthenticatedChatListingIdOtherIdRouteImport } from './routes/_authenticated/chat.$listingId.$otherId'
import { Route as AuthenticatedAdminListingIdRouteImport } from './routes/_authenticated/admin/listing.$id'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCategoryRoute = BrowseCategoryRouteImport.update({
  id: '/browse/$category',
  path: '/browse/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmitListingRoute =
  AuthenticatedSubmitListingRouteImport.update({
    id: '/submit-listing',
    path: '/submit-listing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMySavedRoute = AuthenticatedMySavedRouteImport.update({
  id: '/my-saved',
  path: '/my-saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListingsRoute = AuthenticatedMyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompleteDealerProfileRoute =
  AuthenticatedCompleteDealerProfileRouteImport.update({
    id: '/complete-dealer-profile',
    path: '/complete-dealer-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/account-settings',
    path: '/account-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEditListingIdRoute =
  AuthenticatedEditListingIdRouteImport.update({
    id: '/edit-listing/$id',
    path: '/edit-listing/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin/notifications',
    path: '/admin/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminListingsRoute =
  AuthenticatedAdminListingsRouteImport.update({
    id: '/admin/listings',
    path: '/admin/listings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDealersRoute =
  AuthenticatedAdminDealersRouteImport.update({
    id: '/admin/dealers',
    path: '/admin/dealers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatListingIdOtherIdRoute =
  AuthenticatedChatListingIdOtherIdRouteImport.update({
    id: '/chat/$listingId/$otherId',
    path: '/chat/$listingId/$otherId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminListingIdRoute =
  AuthenticatedAdminListingIdRouteImport.update({
    id: '/admin/listing/$id',
    path: '/admin/listing/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/complete-dealer-profile': typeof AuthenticatedCompleteDealerProfileRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/my-saved': typeof AuthenticatedMySavedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/submit-listing': typeof AuthenticatedSubmitListingRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/listing/$id': typeof ListingIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/user/$id': typeof UserIdRoute
  '/admin/dealers': typeof AuthenticatedAdminDealersRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/edit-listing/$id': typeof AuthenticatedEditListingIdRoute
  '/admin/listing/$id': typeof AuthenticatedAdminListingIdRoute
  '/chat/$listingId/$otherId': typeof AuthenticatedChatListingIdOtherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/complete-dealer-profile': typeof AuthenticatedCompleteDealerProfileRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/my-listings': typeof AuthenticatedMyListingsRoute
  '/my-saved': typeof AuthenticatedMySavedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/submit-listing': typeof AuthenticatedSubmitListingRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/listing/$id': typeof ListingIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/user/$id': typeof UserIdRoute
  '/admin/dealers': typeof AuthenticatedAdminDealersRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/edit-listing/$id': typeof AuthenticatedEditListingIdRoute
  '/admin/listing/$id': typeof AuthenticatedAdminListingIdRoute
  '/chat/$listingId/$otherId': typeof AuthenticatedChatListingIdOtherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/_authenticated/account-settings': typeof AuthenticatedAccountSettingsRoute
  '/_authenticated/complete-dealer-profile': typeof AuthenticatedCompleteDealerProfileRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/my-listings': typeof AuthenticatedMyListingsRoute
  '/_authenticated/my-saved': typeof AuthenticatedMySavedRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/submit-listing': typeof AuthenticatedSubmitListingRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/listing/$id': typeof ListingIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/user/$id': typeof UserIdRoute
  '/_authenticated/admin/dealers': typeof AuthenticatedAdminDealersRoute
  '/_authenticated/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/edit-listing/$id': typeof AuthenticatedEditListingIdRoute
  '/_authenticated/admin/listing/$id': typeof AuthenticatedAdminListingIdRoute
  '/_authenticated/chat/$listingId/$otherId': typeof AuthenticatedChatListingIdOtherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/account-settings'
    | '/complete-dealer-profile'
    | '/messages'
    | '/my-listings'
    | '/my-saved'
    | '/notifications'
    | '/submit-listing'
    | '/browse/$category'
    | '/listing/$id'
    | '/review/$id'
    | '/user/$id'
    | '/admin/dealers'
    | '/admin/listings'
    | '/admin/notifications'
    | '/edit-listing/$id'
    | '/admin/listing/$id'
    | '/chat/$listingId/$otherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/account-settings'
    | '/complete-dealer-profile'
    | '/messages'
    | '/my-listings'
    | '/my-saved'
    | '/notifications'
    | '/submit-listing'
    | '/browse/$category'
    | '/listing/$id'
    | '/review/$id'
    | '/user/$id'
    | '/admin/dealers'
    | '/admin/listings'
    | '/admin/notifications'
    | '/edit-listing/$id'
    | '/admin/listing/$id'
    | '/chat/$listingId/$otherId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/_authenticated/account-settings'
    | '/_authenticated/complete-dealer-profile'
    | '/_authenticated/messages'
    | '/_authenticated/my-listings'
    | '/_authenticated/my-saved'
    | '/_authenticated/notifications'
    | '/_authenticated/submit-listing'
    | '/browse/$category'
    | '/listing/$id'
    | '/review/$id'
    | '/user/$id'
    | '/_authenticated/admin/dealers'
    | '/_authenticated/admin/listings'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/edit-listing/$id'
    | '/_authenticated/admin/listing/$id'
    | '/_authenticated/chat/$listingId/$otherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  BrowseCategoryRoute: typeof BrowseCategoryRoute
  ListingIdRoute: typeof ListingIdRoute
  ReviewIdRoute: typeof ReviewIdRoute
  UserIdRoute: typeof UserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id': {
      id: '/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$category': {
      id: '/browse/$category'
      path: '/browse/$category'
      fullPath: '/browse/$category'
      preLoaderRoute: typeof BrowseCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/submit-listing': {
      id: '/_authenticated/submit-listing'
      path: '/submit-listing'
      fullPath: '/submit-listing'
      preLoaderRoute: typeof AuthenticatedSubmitListingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-saved': {
      id: '/_authenticated/my-saved'
      path: '/my-saved'
      fullPath: '/my-saved'
      preLoaderRoute: typeof AuthenticatedMySavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-listings': {
      id: '/_authenticated/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof AuthenticatedMyListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complete-dealer-profile': {
      id: '/_authenticated/complete-dealer-profile'
      path: '/complete-dealer-profile'
      fullPath: '/complete-dealer-profile'
      preLoaderRoute: typeof AuthenticatedCompleteDealerProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-settings': {
      id: '/_authenticated/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-listing/$id': {
      id: '/_authenticated/edit-listing/$id'
      path: '/edit-listing/$id'
      fullPath: '/edit-listing/$id'
      preLoaderRoute: typeof AuthenticatedEditListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/listings': {
      id: '/_authenticated/admin/listings'
      path: '/admin/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AuthenticatedAdminListingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/dealers': {
      id: '/_authenticated/admin/dealers'
      path: '/admin/dealers'
      fullPath: '/admin/dealers'
      preLoaderRoute: typeof AuthenticatedAdminDealersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$listingId/$otherId': {
      id: '/_authenticated/chat/$listingId/$otherId'
      path: '/chat/$listingId/$otherId'
      fullPath: '/chat/$listingId/$otherId'
      preLoaderRoute: typeof AuthenticatedChatListingIdOtherIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/listing/$id': {
      id: '/_authenticated/admin/listing/$id'
      path: '/admin/listing/$id'
      fullPath: '/admin/listing/$id'
      preLoaderRoute: typeof AuthenticatedAdminListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRoute
  AuthenticatedCompleteDealerProfileRoute: typeof AuthenticatedCompleteDealerProfileRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMyListingsRoute: typeof AuthenticatedMyListingsRoute
  AuthenticatedMySavedRoute: typeof AuthenticatedMySavedRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSubmitListingRoute: typeof AuthenticatedSubmitListingRoute
  AuthenticatedAdminDealersRoute: typeof AuthenticatedAdminDealersRoute
  AuthenticatedAdminListingsRoute: typeof AuthenticatedAdminListingsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedEditListingIdRoute: typeof AuthenticatedEditListingIdRoute
  AuthenticatedAdminListingIdRoute: typeof AuthenticatedAdminListingIdRoute
  AuthenticatedChatListingIdOtherIdRoute: typeof AuthenticatedChatListingIdOtherIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountSettingsRoute: AuthenticatedAccountSettingsRoute,
  AuthenticatedCompleteDealerProfileRoute:
    AuthenticatedCompleteDealerProfileRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMyListingsRoute: AuthenticatedMyListingsRoute,
  AuthenticatedMySavedRoute: AuthenticatedMySavedRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSubmitListingRoute: AuthenticatedSubmitListingRoute,
  AuthenticatedAdminDealersRoute: AuthenticatedAdminDealersRoute,
  AuthenticatedAdminListingsRoute: AuthenticatedAdminListingsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedEditListingIdRoute: AuthenticatedEditListingIdRoute,
  AuthenticatedAdminListingIdRoute: AuthenticatedAdminListingIdRoute,
  AuthenticatedChatListingIdOtherIdRoute:
    AuthenticatedChatListingIdOtherIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  BrowseCategoryRoute: BrowseCategoryRoute,
  ListingIdRoute: ListingIdRoute,
  ReviewIdRoute: ReviewIdRoute,
  UserIdRoute: UserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
